In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [3]:
x = [1,23,34,4,5,12]
x

[1, 23, 34, 4, 5, 12]

In [4]:
y = np.array(x)
y

array([ 1, 23, 34,  4,  5, 12])

In [5]:
type(y)

numpy.ndarray

In [6]:
y.shape

(6,)

In [7]:
y[y>10]

array([23, 34, 12])

In [9]:
y[y%2!=0]

array([ 1, 23,  5])

In [10]:
y+22

array([23, 45, 56, 26, 27, 34])

In [11]:
c = [2,3,4,5,75,34]
c

[2, 3, 4, 5, 75, 34]

In [14]:
z = np.array([x,c])
z

array([[ 1, 23, 34,  4,  5, 12],
       [ 2,  3,  4,  5, 75, 34]])

In [15]:
z[ : , 1: ]

array([[23, 34,  4,  5, 12],
       [ 3,  4,  5, 75, 34]])

In [16]:
z.reshape(4,3)

array([[ 1, 23, 34],
       [ 4,  5, 12],
       [ 2,  3,  4],
       [ 5, 75, 34]])

In [17]:
np.std(z)

21.027098917560856

In [18]:
np.var(z)

442.1388888888889